services:
  mongo:
    image: mongo:8
    container_name: daemondoc-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - daemondoc-mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: daemondoc-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - daemondoc-redis-data:/data

volumes:
  daemondoc-mongo-data:
    external: true
  daemondoc-redis-data:
    name: daemondoc-redis-data
