name: daemondoc-api-server
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - daemondoc-api-network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - daemondoc-api-network
       
networks:
  daemondoc-api-network:
    name: daemondoc-api-network
    driver: bridge