name: daemondoc-api-server
services:
  redis:
    image: redis:7-alpine
    container_name: daemondoc-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - daemondoc-api-network
    volumes:
      - daemondoc-redis-data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - daemondoc-api-network

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - daemondoc-api-network

networks:
  daemondoc-api-network:
    name: daemondoc-api-network
    driver: bridge

volumes:
  daemondoc-redis-data:
    name: daemondoc-redis-data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
